# Generated by Django 4.1.2 on 2022-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0002_remove_post_musics_post-music'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
